# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999e9935f90621a732c6d3ed72f28b776f4c7675b075f50969f5fb6f2a532debe24beafde58e231187ff787d4de94ca5c1c880f5b7961c26ac28ccc848000ce6

test:
  secret_key_base: 7677d993b0b684c42461f7579780442e5014201eb54235099a21e66b64ae999bb1be607c6977002c63aa8ef8d61c10c1920c2e8a4476290ebda6034432fef4a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
